from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1425, 1012)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 30, 1351, 511))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_SSH = QtWidgets.QWidget()
        self.tab_SSH.setObjectName("tab_SSH")
        self.groupBox = QtWidgets.QGroupBox(self.tab_SSH)
        self.groupBox.setGeometry(QtCore.QRect(30, 20, 631, 401))
        self.groupBox.setObjectName("groupBox")

        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(330, 240, 101, 21))
        self.pushButton.setObjectName("pushButton")

        #TODO: 添加选择文件功能
        self.toolButton_selectPKeyPath = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_selectPKeyPath.setGeometry(QtCore.QRect(320, 130, 21, 21))
        self.toolButton_selectPKeyPath.setObjectName("toolButton_selectPKeyPath")

        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(174, 57, 139, 169))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.hostIpInput = QtWidgets.QLineEdit(self.layoutWidget)
        self.hostIpInput.setObjectName("hostIpInput")
        self.verticalLayout.addWidget(self.hostIpInput)
        self.portInput = QtWidgets.QLineEdit(self.layoutWidget)
        self.portInput.setObjectName("portInput")
        self.verticalLayout.addWidget(self.portInput)
        self.pathToPrivateKeyInput = QtWidgets.QLineEdit(self.layoutWidget)
        self.pathToPrivateKeyInput.setObjectName("pathToPrivateKeyInput")
        self.verticalLayout.addWidget(self.pathToPrivateKeyInput)
        self.pswdToKeyInput = QtWidgets.QLineEdit(self.layoutWidget)
        self.pswdToKeyInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pswdToKeyInput.setObjectName("pswdToKeyInput")
        self.verticalLayout.addWidget(self.pswdToKeyInput)
        self.UsrnInput = QtWidgets.QLineEdit(self.layoutWidget)
        self.UsrnInput.setObjectName("UsrnInput")
        self.verticalLayout.addWidget(self.UsrnInput)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 59, 127, 151))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.tabWidget.addTab(self.tab_SSH, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1425, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.toolButton_selectPKeyPath.clicked.connect(self.pathToPrivateKeyInput.paste)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "wzlk8toolkit"))
        self.groupBox.setTitle(_translate("MainWindow", "k8mars connection"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.toolButton_selectPKeyPath.setText(_translate("MainWindow", "..."))
        self.label.setText(_translate("MainWindow", "Host Name:"))
        self.label_2.setText(_translate("MainWindow", "Port:"))
        self.label_3.setText(_translate("MainWindow", "Path to Private Key:"))
        self.label_4.setText(_translate("MainWindow", "Password for the key:"))
        self.label_5.setText(_translate("MainWindow", "Username:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_SSH), _translate("MainWindow", "SSH"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
